# @Author: Georg C. Ganzenmueller, Albert-Ludwigs Universitaet Freiburg, Germany
# @Date:   2024-12-19 17:08:28
# @Last Modified by:   Georg C. Ganzenmueller, Albert-Ludwigs Universitaet Freiburg, Germany
# @Last Modified time: 2024-12-20 22:24:54
title: Gips-Schüle Chair for Sustainable Systems Engineering
description: Gips-Schüle Chair for Sustainable Systems Engineering, INATECH, University of Freiburg. Mechanical behaviour of materials, high strain rate testing, metamaterials and X-ray CT.
url: "https://ggalu.github.io"

remote_theme: alexander-heimbuch/millidocs

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - makefile
  - millidocs.gemspec
  - vendor

sass:
  sass_dir: _sass
  style: compressed
